<a href="https://colab.research.google.com/github/Oscar19922017/Ciencia-de-Datos/blob/master/Introduccion_Python_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduccion a Python**
**Oscar Gaspar - Maestría en Métodos Cuantitativos**

"Se trata de un lenguaje de programación de alto nivel multiparadigma, ya que soporta orientación a objetos, programación imperativa y, en menor medida, programación funcional. Es un lenguaje interpretado, dinámico y multiplataforma"

Este lenguaje fue creado a principios de los noventa por Guido van Rossum en los Países Bajos.

El nombre del lenguaje proviene de la afición de su creador por los humoristas británicos Monty Python.

Es administrado por la Python Software Foundation. Posee una licencia de código abierto, denominada Python Software Foundation License,3​ que es compatible con la Licencia pública general de GNU a partir de la versión 2.1.1

**Python para Ciencia de Datos**

Según lo revelado por los resultados de una encuesta realizada por Kaggle una plataforna de científicos de datos, Python  es el más usado en cuanto a lenguaje de programación, seguido de SQL y R para el tema de ciencia de Datos


# **Información básica**
Un algoritmo es una lista de instrucciones que serán desarrolladas en un orden específico con el objetivo de resolver un problema o realizar una operación. Por ejemplo, un algoritmo para encender el carro puede ser:

Abrir la puerta.
Entrar al carro y tomar asiento.
Insertar la llave en el switch.
Girar la llave en sentido horario y mantenerla hasta que el carro encienda.
Los pasos anteriormente descritos tienen un orden lógico en el que son ejecutados, y para este algoritmo en particular, si intentamos realizar alguno de ellos en desorden no obtendríamos el resultado que queremos. Antes de girar la llave debemos haberla insertado. No podemos entrar al carro sin haber abierto la puerta.

Generalmente, el buen diseño de un algoritmo se basa en responder las siguientes preguntas:

¿Cuál es mi objetivo?
¿Con qué información cuento para alcanzarlo? (datos de entrada)
¿Que información voy a obtener al alcanzar mi objetivo? (datos de salida)
¿Qué cálculos o procesos debo realizar?
Variables
Un lenguaje de programación, sea cual sea, necesita poder tener acceso a y tener la capacidad de modificar información. Esto se logra por medio del uso de variables. Para utilizar una variable dentro de un programa, es necesario declararla primero.

Declaración de Variables
Para declarar una variable, primero debemos darle un nombre cualquiera a la variable utilizando letras y números sin espacios, teniendo en cuenta que las mayúsculas importan. Luego de darle un nombre a la variable, se le asigna un valor por medio del operador “=”. De esta forma, el programa puede separar un bloque de memoria para la variable y guardar en dicho bloque el valor de esta. A diferencia de otros lenguajes de programación, en Python 3 no se puede declarar una variable sin asignarle un valor.

Existen varios tipos de variables, según el tipo de información con la que se desee trabajar dentro de un programa.

**Explicación tomada del curso fundamentos de programación de la Universidad Nacional sede Medellín** 

# **Librerias para Ciencia de Datos**

* **Numpy** :NumPy es una biblioteca de Python muy popular para el procesamiento de matrices y matrices multidimensionales de gran tamaño
* **Scipy** : SciPy es una biblioteca muy popular entre los entusiastas del aprendizaje automático, ya que contiene diferentes módulos para optimización, álgebra lineal, integración y estadísticas.
* **Scikit-learn** : Skikit-learn es una de las bibliotecas ML más populares para algoritmos ML clásicos. Está construido sobre dos bibliotecas básicas de Python, a saber, NumPy y SciPy. Scikit-learn admite la mayoría de los algoritmos de aprendizaje supervisados ​​y no supervisados.
* **Theano** Todos sabemos que Machine Learning es básicamente matemática y estadística. Theano es una popular biblioteca de Python que se utiliza para definir, evaluar y optimizar expresiones matemáticas que involucran matrices multidimensionales de manera eficiente. Se logra optimizando la utilización de la CPU y la GPU. Se usa ampliamente para pruebas unitarias y autoverificaciones para detectar y diagnosticar diferentes tipos de errores.
* **TensorFlow** : TensorFlow es una biblioteca de código abierto muy popular para el cómputo numérico de alto rendimiento desarrollado por el equipo de Google Brain en Google. Como su nombre lo indica, Tensorflow es un marco que implica definir y ejecutar cálculos que involucran tensores. Puede entrenar y ejecutar redes neuronales profundas que pueden usarse para desarrollar varias aplicaciones de IA
* **Keras** : Keras es una biblioteca de Machine Learning muy popular para Python. Es una API de redes neuronales de alto nivel capaz de ejecutarse sobre TensorFlow, CNTK o Theano. Se puede ejecutar sin problemas tanto en la CPU como en la GPU. Keras hace que sea realmente para principiantes de ML construir y diseñar una red neuronal.
* **PyTorch** : PyTorch es una biblioteca de aprendizaje automático de código abierto popular para Python basada en Torch, que es una biblioteca de aprendizaje automático de código abierto que se implementa en C con un contenedor en Lua. Tiene una amplia selección de herramientas y bibliotecas que admite la visión por computadora, el procesamiento del lenguaje natural (PNL) y muchos más programas de ML. Permite a los desarrolladores realizar cálculos en tensores con aceleración de GPU y también ayuda a crear gráficos computacionales.
* **Pandas** : Pandas es una biblioteca de Python popular para el análisis de datos. No está directamente relacionado con el aprendizaje automático. Como sabemos, el conjunto de datos debe estar preparado antes del entrenamiento. 
* **Matplotlib** : Matpoltlib es una biblioteca Python muy popular para la visualización de datos. Al igual que Pandas, no está directamente relacionado con el aprendizaje automático. Es particularmente útil cuando un programador quiere visualizar los patrones en los datos


**Instalar Librerias**

conda y pip son herramientas para manejar y desplegar aplicaciones, ambientes y paquetes.



**Instalacion en el ambiente Anaconda**

In [0]:
#Con comdando conda
#conda install numpy
#con comando pip
#pip install numpy
#Para forzar la instalacion
#conda install -c conda-forge numpy

**Instalacion en el ambiente Google Colab**

In [0]:
#!pip install -q keras 

**Importar Librerias**

**Forma Directa**

In [0]:
import sys
import os
import numpy
import pandas

**Dando un alias y es mas util**

In [0]:
import numpy as np
import pandas as pd

**Importando un submodulo en vez de la Libreria**

In [0]:
import matplotlib.pyplot as plt

**Importando Funciones de la libreria**

In [0]:
from random import  random, uniform,gauss

# **Primeros Pasos con Python**

**Atajos**

* Nueva celda debajo : “Esc+b”
* Nueva celda por encima : “Esc+a”
* Borrar Celda: “Esc+D+D”
* Comentar Region:”Crtl+/” or “Ctrl+}”
* SHIFT + M = Combina múltiples celdas seleccionadas en una celda..
* CTRL + SHIFT + – = Divide la celda actual en dos celdas desde donde está el cursor.


**Calculadora**

In [0]:
6+4 # Suma

10

In [0]:
9-2 # Resta

7

In [0]:
8**4 # Potencia

4096

In [0]:
8/4 # Division

2.0

In [0]:
9*8 # Multiplicacion

72

In [0]:
78%5 # Modulo

3

# **Variables en Pyhon**

### ¿Que es una Variable?

**"En programación, una variable está formada por un espacio en el sistema de almacenaje (memoria principal de un ordenador) y un nombre simbólico (un identificador) que está asociado a dicho espacio. Ese espacio contiene una cantidad de información conocida o desconocida, es decir un valor. El nombre de la variable es la forma usual de referirse al valor almacenad"**

Tipos de Variables: Enteros, flotantes, cadenas de caracteres, boleanos, bytes, complejos

**Para Asignar un valor a una Variable usamos =**

**Enteros y Flotantes**

In [0]:
## Para guardar informacion Numerica Tipo Entero, en Python int
a=1 
b=3
a+b 
# para mostrar el contenido de una variable usamos print
print(a)
print(b)
print(a+b)

1
3
4


In [0]:
## Para Formato decimal o float en python
d= 1.145455

In [0]:
## Para conocer el tipo de Variable, usamos comando type
print(type(a))
print(type(d))

<class 'int'>
<class 'float'>


In [0]:
# Para transformar un entero a flotante ( int a float)
int(5.25)

5

In [0]:
# Para Transformar un float a int
float(5)

5.0

**Cadenas de Caracteres o strings** 

In [0]:
"Juan"+"Perez"

'JuanPerez'

In [0]:
## Asignar a una Variable
nombre = "Juan"+" "+"Perez"
print(nombre)

Juan Perez


In [0]:
## Repetir
nombre*3

'Juan PerezJuan PerezJuan Perez'

In [0]:
# Separar la cadena
nombre.split(" ")# separa por espacios

['Juan', 'Perez']

In [0]:
# Longitud de la cadena
len(nombre)

10

In [0]:
# Tipo
type(nombre)

str

**Expresiones y valores booleanos**

In [0]:
type(True)



bool

In [0]:
5 == 5

True

El operador == es uno de los operadores de comparación; los otros son:
* x != y    : x no es igual a y
* x > y     : x es mayor que y
* x < y     : x es menor que y
* x >= y    : x es mayor o igual que y
* x <= y    : x es menor o igual que y

**Operadores lógicos**

Existen tres operadores lógicos: and, or, y not. La semántica (significado) de estos operadores es similar a sus significados en inglés (en español “y”, “o” y “no”). Por ejemplo, x > 0 and x < 10 es verdadero sólo si x es mayor que 0 y menor que 10.

n % 2 == 0 or n % 3 == 0 es verdadero si cualquiera de las condiciones es verdadera, o sea, si el número es divisible por 2 o por 3.

Finalmente, el operador not niega una expresión booleana, de forma que not(x > y) es verdadero si (x > y) es falso, o sea, si x es menor o igual que y.


# **Extructuras de Control o Condicionales**
Para escribir programas útiles, casi siempre necesitamos la capacidad de comprobar ciertas condiciones y cambiar el comportamiento del programa como corresponda. Las sentencias condicionales nos dan esta capacidad. La forma más sencilla es la sentencia if, fue la base para la programacion logica, el primer enfoque de dar instrucciones a las Maquinas

**If else**

In [0]:
a = 10

if(a <= 5):
	print("a es menor o igual que 5")
else:
	print("a es mayor que 5")

a es mayor que 5


**También podemos anidar if como en otros lenguajes pero recuerda la indentación**

In [0]:
a = 4

if(a <= 5):
	if(a == 5):
		print("a es igual que 5")
	else:
		print("a es menor que 5")
else:
	print("a es mayor que 5")

a es menor que 5


**En python no existen switches, como en Java**

In [0]:
dia="Sabado"

if(dia == "Lunes"):
	print("Lunes otra vez no!!")
elif(dia == "Martes"):
	print("Los martes son pesados")
elif(dia == "Miercoles"):
	print("Casi mitad de semana")
elif(dia == "Jueves"):
	print("Jueves como me gustas")
elif(dia == "Viernes"):
	print("Por fin Viernes :)")
elif(dia == "Sabado"):
	print("Sabadoooo")
elif(dia == "Domingo"):
	print("Mañana sera LUNESSS")
else:
	print("Eso no es un dia")

Sabadoooo


# **Funciones**
Una función es una porción o bloque de código reutilizable que se encarga de realizar una determinada tarea." Python es un lenguaje que nos da mucha flexibilidad al momento de crear funciones, en esté tutorial se darán cuenta porque.

In [32]:
# Se crean con el comando def
def Suma_dos_Numeros(x, y): # parametros x y Y
    return x + y

Suma_dos_Numeros(1, 2)

3

**Tomar un tercer parámetro opcional. El uso printpermite la impresión de múltiples expresiones dentro de una sola celda.**



In [33]:
def Suma_dos_Numeros(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(Suma_dos_Numeros(1, 2)) ## tomo dos parametros
print(Suma_dos_Numeros(1, 2, 3)) ### Tomo tres Parametros

3
6


**Asignar Una función a una variable A**

In [34]:
def Suma_dos_Numeros(x,y):
    return x+y

a = Suma_dos_Numeros
a(1,2)

3

# **Extructura de Datos**

**Listas**

Una lista es una estructura de datos y un tipo de dato en python con características especiales. Lo especial de las listas en Python es que nos permiten almacenar cualquier tipo de valor como enteros, cadenas y hasta otras funciones; por ejemplo:

In [0]:
# se crean con [] y se pueden modificar
lista = [1, 2.5, 'DevCode', [5,6] ,4]

In [37]:
## Acceder al contenido
lista[0] ## Empieza en la posicion cero

1

In [38]:
lista[1]

2.5

In [39]:
lista[-1] ## conocer el ultimo dato

4

In [40]:
#Agregar Nuevos Datos a la Lista
lista.append(10) 
lista.append([2,5]) 
lista

[1, 2.5, 'DevCode', [5, 6], 4, 10, [2, 5]]

Extend también nos permite agregar elementos dentro de una lista, pero a diferencia de append al momento de agregar una lista, cada elemento de esta lista se agrega como un elemento más dentro de la otra lista.

In [41]:
lista.extend([2,5])
lista

[1, 2.5, 'DevCode', [5, 6], 4, 10, [2, 5], 2, 5]

**Tuplas**

En Python, una tupla es un conjunto ordenado e inmutable de elementos del mismo o diferente tipo.

Las tuplas se representan escribiendo los elementos entre paréntesis y separados por comas y no se pueden modificar

In [42]:
x = (1, 'a', 2, 'b')
type(x) ## las Tuplas no se pueden Cambiar el contenido

tuple

**Diccionarios**

Un Diccionario es una estructura de datos y un tipo de dato en Python con características especiales que nos permite almacenar cualquier tipo de valor como enteros, cadenas, listas e incluso otras funciones. Estos diccionarios nos permiten además identificar cada elemento por una clave (Key).

Para definir un diccionario, se encierra el listado de valores entre llaves. Las parejas de clave y valor se separan con comas, y la clave y el valor se separan con dos puntos.

In [43]:
diccionario = {'nombre' : 'Carlos', 'edad' : 22, 'cursos': ['Python','Django','JavaScript'] }
print(diccionario)


{'nombre': 'Carlos', 'edad': 22, 'cursos': ['Python', 'Django', 'JavaScript']}


Podemos acceder al elemento de un Diccionario mediante la clave de este elemento, como veremos a continuación:

In [44]:
print (diccionario['nombre'] )#Carlos
print(diccionario['edad']) #22
print (diccionario['cursos']) #['Python','Django','JavaScript']

Carlos
22
['Python', 'Django', 'JavaScript']


**Arrays**

NumPy proporciona un tipo de matriz N-dimensional, el ndarray, que describe una colección de "elementos" del mismo tipo. Los elementos se pueden indexar utilizando, por ejemplo, N enteros.

Todos los ndarrays son homogéneos: cada elemento ocupa el mismo tamaño de bloque de memoria, y todos los bloques se interpretan exactamente de la misma manera. La forma de interpretar cada elemento de la matriz se especifica mediante un objeto de tipo de datos separado, uno de los cuales está asociado con cada matriz. Además de los tipos básicos (enteros, flotantes, etc.), los objetos de tipo de datos también pueden representar estructuras de datos.

Un elemento extraído de una matriz, por ejemplo, mediante indexación, está representado por un objeto Python cuyo tipo es uno de los tipos escalares de matriz creados en NumPy. Los escalares de matriz permiten una fácil manipulación de arreglos de datos también más complicados

In [0]:
import numpy as np

In [47]:
#Creando Arrays
#Desde una lista a una lista

mylist = [1, 2, 3] ## 
x = np.array(mylist)
x

array([1, 2, 3])

In [48]:
#Directemente
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [49]:
#Multidimensional
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
# Conocer la Dimension
m.shape

(2, 3)

In [54]:
# Operaciones Básicas
x=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(x)
y = np.arange(0,9).reshape((3,3))
print(y)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [55]:
## Operaciones
x+y

array([[ 1,  3,  5],
       [ 8, 10, 12],
       [14, 16, 18]])

In [56]:
y/x

array([[0.        , 0.5       , 0.66666667],
       [0.6       , 0.66666667, 0.71428571],
       [0.75      , 0.77777778, 0.8       ]])

In [57]:
np.matmul(x,y)

array([[ 24,  30,  36],
       [ 60,  78,  96],
       [ 87, 114, 141]])

**SERIES**

Series es la estructura de datos para una sola columna de una DataFrame, no solo conceptualmente, sino que literalmente, es decir, los datos de una DataFrame se almacenan en la memoria como una colección de Series.

In [0]:
import pandas as pd

In [60]:
Variables = ['Nombre', 'Direccion', 'Cargo']
pd.Series(Variables)

0       Nombre
1    Direccion
2        Cargo
dtype: object

In [61]:
Numeros = [1, 2, 3]
pd.Series(Numeros )

0    1
1    2
2    3
dtype: int64

In [62]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
## Convertimos diccionario en una Serie
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [63]:
s.iloc[3] ## Acceder

'South Korea'

In [64]:
s.loc['Golf']

'Scotland'

In [65]:
s[3]

'South Korea'

In [66]:
s['Golf']

'Scotland'

In [0]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)

In [68]:
s.iloc[0]

'Bhutan'

In [69]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0    100.0
1    120.0
2    101.0
3      3.0
dtype: float64

**DataFrame**

El DataFrame es una estructura de 2 dimensiones etiquetada donde podemos almacenar datos de diferentes tipos. DataFrame es similar a una tabla SQL o una hoja de cálculo de Excel.

In [70]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5
Store 2  Vinod      Bird Seed   5.0

In [71]:
## Consultando contenido
df.loc['Store 2']

Name                  Vinod
Item Purchased    Bird Seed
Cost                      5
Name: Store 2, dtype: object

In [72]:
df.loc['Store 1']

Name Item Purchased  Cost
Store 1  Chris       Dog Food  22.5
Store 1  Kevyn   Kitty Litter   2.5

In [73]:
df.loc['Store 1', 'Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [75]:
## Trasponer
df.T

Store 1       Store 1    Store 2
Name               Chris         Kevyn      Vinod
Item Purchased  Dog Food  Kitty Litter  Bird Seed
Cost                22.5           2.5          5

In [76]:
df.T.loc['Cost']

Store 1    22.5
Store 1     2.5
Store 2       5
Name: Cost, dtype: object

In [78]:
## CREAR COPIA
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Name Item Purchased  Cost
Store 2  Vinod      Bird Seed   5.0

**BORRAR VARIABLE**

In [79]:
del copy_df['Name']
copy_df

Item Purchased  Cost
Store 2      Bird Seed   5.0

In [80]:
#Crear Variable
df['Location'] = None
d

1.145455

# **Importar Archivos**

In [82]:
#Importar csv
df = pd.read_csv(r'olympics.csv')
df.head()

0         1     2     3  ...    12    13    14              15
0                NaN  № Summer  01 !  02 !  ...  01 !  02 !  03 !  Combined total
1  Afghanistan (AFG)        13     0     0  ...     0     0     2               2
2      Algeria (ALG)        12     5     2  ...     5     2     8              15
3    Argentina (ARG)        23    18    24  ...    18    24    28              70
4      Armenia (ARM)         5     1     2  ...     1     2     9              12

[5 rows x 16 columns]

In [83]:
# Importar Excle xlsx
df = pd.read_excel(r'example.xlsx', sheet_name='example')
df.head(5)

Unnamed: 0 first_name last_name  age  amount_1 amount_2
0           0     Sigrid   Mannock   27      7.17     8.06
1           1        Joe   Hinners   31      1.90        ?
2           2  Theodoric    Rivers   36      1.11      5.9
3           3    Kennedy   Donnell   53      1.41        ?
4           4    Beatrix   Parlett   48      6.69        ?